#  Analyze what is the fuel consumption (L/100k) rate for the disel car? In provided database. (part 1)
https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data
<br>
Cheat sheet:
* 0) download data
* 1) find and replace non-nesecary string, symbols, etc
* 2) check if there are any missing (blank) entrys in data
* 3) if there are, than find how much there is, where their are, and replace it (for example with mean) or delete

## 0) Dowload data

In [1]:
import pandas as pd
import numpy as np
# save the url path, before any action 
# check what it is
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
# create a dataframe object
df = pd.read_csv(url,header=None)

df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

Numbered headers are not exactly readble. We will change them as in information about the table provided at <br>
https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.names

In [2]:
# taken headers names
features_names = "symboling:          normalized-losses: make:                   fuel-type:         aspiration:        num-of-doors:      body-style:        drive-wheels:      engine-location:   wheel-base:        length:            width:             height:            curb-weight:       engine-type:       num-of-cylinders:  engine-size:       fuel-system:       bore:              stroke:            compression-ratio: horsepower:        peak-rpm:          city-mpg:          highway-mpg:       price:          "
# we filter unused spaces and split words to a list
features_list = features_names.split()
features_list = [el[:-1] for el in features_list]
# print(features_list)
#print(len(features_list))
# there is 26 features, so evertyhink went fine
headers = features_list 
df.columns = headers
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

When everything is set up we save our table.

In [3]:
# paste a desired path
#path = "your path"
#df.to_csv('path')
"""
i do not want to have inexing numbers 
so with index=False we make sure
that those won't appear
""" 
df.to_csv('autos.csv', index=False)